name: GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -c Release --no-build -o rel
    - name: Add NoJekyll
      run: ls rel/wwwroot && echo "W" && touch rel/wwwroot/.nojekyll && echo "Done" && ls -a rel/wwwroot
    - name: Deploy to GH Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: 'rel/wwwroot'
        CLEAN: true
        GIT_CONFIG_NAME: 'Nikhil Hari'
        GIT_CONFIG_EMAIL: 'nikhil_hari@live.com'
        REPOSITORY_NAME: 'CruciformHawk7/cruciformhawk7.github.io'
        BRANCH: 'master'
        
